CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251002160659_AddAutoApprovalModeToClient') THEN
    ALTER TABLE "Clients" ADD "AutoApprovalMode" integer NOT NULL DEFAULT 0;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251002160659_AddAutoApprovalModeToClient') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20251002160659_AddAutoApprovalModeToClient', '9.0.9');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251002183251_Initial') THEN
    CREATE TABLE "AuthorizationCodes" (
        "Id" uuid NOT NULL,
        "Code" character varying(200) NOT NULL,
        "ClientId" text NOT NULL,
        "UserId" uuid NOT NULL,
        "RedirectUri" text NOT NULL,
        "ScopesJson" text NOT NULL,
        "Nonce" text,
        "CodeChallenge" text,
        "CodeChallengeMethod" character varying(10),
        "ExpiresAt" timestamp with time zone NOT NULL,
        "Consumed" boolean NOT NULL,
        CONSTRAINT "PK_AuthorizationCodes" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251002183251_Initial') THEN
    CREATE TABLE "Consents" (
        "Id" uuid NOT NULL,
        "UserId" uuid NOT NULL,
        "ClientId" text NOT NULL,
        "ScopesJson" text NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "RevokedAt" timestamp with time zone,
        CONSTRAINT "PK_Consents" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251002183251_Initial') THEN
    CREATE TABLE "DataProtectionKeys" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "FriendlyName" character varying(200),
        "Xml" text NOT NULL,
        CONSTRAINT "PK_DataProtectionKeys" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251002183251_Initial') THEN
    CREATE TABLE "IdentityProviders" (
        "Id" uuid NOT NULL,
        "Name" character varying(150) NOT NULL,
        "DisplayName" character varying(200),
        "Type" integer NOT NULL,
        "Enabled" boolean NOT NULL DEFAULT TRUE,
        "IsDefault" boolean NOT NULL DEFAULT FALSE,
        "LogoUrl" character varying(2000),
        "SortOrder" integer NOT NULL DEFAULT 0,
        "ConfigJson" character varying(8000),
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_IdentityProviders" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251002183251_Initial') THEN
    CREATE TABLE "LogoutRedirectReferences" (
        "Id" character varying(64) NOT NULL,
        "ClientId" character varying(200) NOT NULL,
        "RedirectUri" character varying(2000) NOT NULL,
        "State" character varying(400),
        "CreatedAt" timestamp with time zone NOT NULL,
        "ExpiresAt" timestamp with time zone NOT NULL,
        "Used" boolean NOT NULL DEFAULT FALSE,
        CONSTRAINT "PK_LogoutRedirectReferences" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251002183251_Initial') THEN
    CREATE TABLE "PushedAuthorizationRequests" (
        "Id" uuid NOT NULL,
        "RequestUri" character varying(512),
        "ClientId" text NOT NULL,
        "RequestJson" text NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "ExpiresAt" timestamp with time zone NOT NULL,
        "Consumed" boolean NOT NULL,
        CONSTRAINT "PK_PushedAuthorizationRequests" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251002183251_Initial') THEN
    CREATE TABLE "QrLoginSessions" (
        "Id" uuid NOT NULL,
        "SessionToken" character varying(128) NOT NULL,
        "SessionTokenHash" character varying(64),
        "ClientId" character varying(200) NOT NULL,
        "ReturnUrl" character varying(2000) NOT NULL,
        "CodeChallenge" character varying(128) NOT NULL,
        "CodeChallengeMethod" character varying(10) NOT NULL,
        "State" character varying(200) NOT NULL,
        "Nonce" character varying(200),
        "Scope" character varying(1000) NOT NULL,
        "Status" integer NOT NULL,
        "UserId" uuid,
        "AuthorizationCode" character varying(200),
        "CreatedAt" timestamp with time zone NOT NULL,
        "ExpiresAt" timestamp with time zone NOT NULL,
        "ScannedAt" timestamp with time zone,
        "AuthenticatedAt" timestamp with time zone,
        "MobileUserAgent" character varying(500),
        "MobileIpAddress" character varying(100),
        CONSTRAINT "PK_QrLoginSessions" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251002183251_Initial') THEN
    CREATE TABLE "Realms" (
        "Id" uuid NOT NULL,
        "Name" character varying(100) NOT NULL,
        "DisplayName" character varying(200),
        "CreatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_Realms" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251002183251_Initial') THEN
    CREATE TABLE "RevocationAudits" (
        "Id" uuid NOT NULL,
        "ClientId" text NOT NULL,
        "TokenHash" character varying(200) NOT NULL,
        "TokenType" character varying(20),
        "IpAddress" character varying(100),
        "CreatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_RevocationAudits" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251002183251_Initial') THEN
    CREATE TABLE "Scopes" (
        "Name" character varying(100) NOT NULL,
        "Description" character varying(200),
        "IsExposed" boolean NOT NULL,
        CONSTRAINT "PK_Scopes" PRIMARY KEY ("Name")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251002183251_Initial') THEN
    CREATE TABLE "SigningKeys" (
        "Id" uuid NOT NULL,
        "Kid" text NOT NULL,
        "Alg" text NOT NULL,
        "JwkJson" text NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "RetiredAt" timestamp with time zone,
        CONSTRAINT "PK_SigningKeys" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251002183251_Initial') THEN
    CREATE TABLE "Tokens" (
        "Id" uuid NOT NULL,
        "Type" character varying(20) NOT NULL,
        "TokenHash" character varying(200) NOT NULL,
        "UserId" uuid NOT NULL,
        "ClientId" text NOT NULL,
        "ScopesJson" text NOT NULL,
        "Audience" character varying(200),
        "Jti" character varying(64),
        "CnfJkt" character varying(200),
        "CreatedAt" timestamp with time zone NOT NULL,
        "ExpiresAt" timestamp with time zone NOT NULL,
        "RevokedAt" timestamp with time zone,
        "ReplacedById" uuid,
        "ActJson" text,
        "DelegationDepth" integer NOT NULL DEFAULT 0,
        CONSTRAINT "PK_Tokens" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251002183251_Initial') THEN
    CREATE TABLE "Users" (
        "Id" uuid NOT NULL,
        "Username" character varying(200) NOT NULL,
        "PasswordHash" text NOT NULL,
        "PasswordSalt" text,
        "HashAlgorithm" text NOT NULL,
        "Email" character varying(256),
        "NormalizedEmail" character varying(256),
        "EmailVerified" boolean NOT NULL,
        "EmailVerifiedAt" timestamp with time zone,
        "Name" character varying(200),
        "CreatedAt" timestamp with time zone NOT NULL,
        "TotpSecret" character varying(200),
        "TotpEnabled" boolean NOT NULL,
        CONSTRAINT "PK_Users" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251002183251_Initial') THEN
    CREATE TABLE "IdentityProviderClaimMappings" (
        "Id" uuid NOT NULL,
        "IdentityProviderId" uuid NOT NULL,
        "ExternalClaim" character varying(200) NOT NULL,
        "LocalClaim" character varying(200) NOT NULL,
        "Transform" character varying(200),
        "Order" integer NOT NULL DEFAULT 0,
        CONSTRAINT "PK_IdentityProviderClaimMappings" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_IdentityProviderClaimMappings_IdentityProviders_IdentityPro~" FOREIGN KEY ("IdentityProviderId") REFERENCES "IdentityProviders" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251002183251_Initial') THEN
    CREATE TABLE "IdentityProviderKeys" (
        "Id" uuid NOT NULL,
        "IdentityProviderId" uuid NOT NULL,
        "Purpose" integer NOT NULL,
        "Jwk" character varying(8000) NOT NULL,
        "Alg" character varying(20) NOT NULL,
        "Active" boolean NOT NULL DEFAULT TRUE,
        "Publishable" boolean NOT NULL,
        "Kid" character varying(200),
        "CreatedAt" timestamp with time zone NOT NULL,
        "ExpiresAt" timestamp with time zone,
        CONSTRAINT "PK_IdentityProviderKeys" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_IdentityProviderKeys_IdentityProviders_IdentityProviderId" FOREIGN KEY ("IdentityProviderId") REFERENCES "IdentityProviders" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251002183251_Initial') THEN
    CREATE TABLE "Clients" (
        "Id" uuid NOT NULL,
        "ClientId" character varying(200) NOT NULL,
        "ClientName" text,
        "RequirePkce" boolean NOT NULL,
        "RequireConsent" boolean NOT NULL,
        "ClientSecretHash" character varying(500),
        "RealmId" uuid NOT NULL,
        "IntrospectionAudiencesJson" character varying(2000),
        "PublicJwksJson" character varying(8000),
        "PublicJwksUri" character varying(2000),
        "RequirePar" boolean NOT NULL DEFAULT FALSE,
        "IntrospectionResponseFieldsJson" character varying(2000),
        "IntrospectionMtlsThumbprintsJson" character varying(2000),
        "AllowedLoginRedirectUrisJson" character varying(4000),
        "AllowedLogoutRedirectUrisJson" character varying(4000),
        "AllowLocalLogin" boolean NOT NULL DEFAULT TRUE,
        "AllowExternalIdp" boolean NOT NULL DEFAULT TRUE,
        "AllowQrLogin" boolean NOT NULL DEFAULT FALSE,
        "LoginStyleKey" character varying(50),
        "M2MAllowedAudiencesJson" character varying(2000),
        "M2MAccessTokenLifetimeSeconds" integer,
        "AllowClientSecretBasic" boolean NOT NULL DEFAULT TRUE,
        "AllowClientSecretPost" boolean NOT NULL DEFAULT TRUE,
        "AllowPrivateKeyJwt" boolean NOT NULL DEFAULT TRUE,
        "M2MMtlsThumbprintsJson" character varying(2000),
        "AllowExternalAutoProvision" boolean NOT NULL DEFAULT TRUE,
        "AllowExternalEmailLinking" boolean NOT NULL DEFAULT TRUE,
        "RequireEmailLinkConfirmation" boolean NOT NULL DEFAULT TRUE,
        "FrontChannelLogoutUri" character varying(2000),
        "FrontChannelLogoutSessionRequired" boolean NOT NULL DEFAULT TRUE,
        "BackChannelLogoutUri" character varying(2000),
        "BackChannelLogoutSessionRequired" boolean NOT NULL DEFAULT TRUE,
        "OboEnabled" boolean,
        "OboAllowedSourceAudiencesJson" character varying(2000),
        "OboAllowedTargetAudiencesJson" character varying(2000),
        "OboAllowedScopesJson" character varying(2000),
        "OboMaxDelegationDepth" integer,
        "OboMaxLifetimeMinutes" integer,
        "OboDpopMode" integer,
        "OboAllowedCallersJson" character varying(2000),
        "AutoApprovalMode" integer NOT NULL,
        CONSTRAINT "PK_Clients" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Clients_Realms_RealmId" FOREIGN KEY ("RealmId") REFERENCES "Realms" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251002183251_Initial') THEN
    CREATE TABLE "Roles" (
        "Id" uuid NOT NULL,
        "Name" character varying(100) NOT NULL,
        "RealmId" uuid NOT NULL,
        "IsActive" boolean NOT NULL,
        CONSTRAINT "PK_Roles" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Roles_Realms_RealmId" FOREIGN KEY ("RealmId") REFERENCES "Realms" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251002183251_Initial') THEN
    CREATE TABLE "ExternalIdentities" (
        "Id" uuid NOT NULL,
        "Issuer" character varying(2000) NOT NULL,
        "Subject" character varying(400) NOT NULL,
        "UserId" uuid NOT NULL,
        "ProviderName" character varying(150),
        "CreatedAt" timestamp with time zone NOT NULL,
        "LastSeenAt" timestamp with time zone NOT NULL,
        "ClaimsJson" character varying(4000),
        CONSTRAINT "PK_ExternalIdentities" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_ExternalIdentities_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251002183251_Initial') THEN
    CREATE TABLE "UserAlternativeEmails" (
        "Id" uuid NOT NULL,
        "UserId" uuid NOT NULL,
        "Email" character varying(256) NOT NULL,
        "NormalizedEmail" character varying(256) NOT NULL,
        "IsVerified" boolean NOT NULL,
        "VerifiedAt" timestamp with time zone,
        CONSTRAINT "PK_UserAlternativeEmails" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_UserAlternativeEmails_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251002183251_Initial') THEN
    CREATE TABLE "BackchannelLogoutNotifications" (
        "Id" uuid NOT NULL,
        "ClientDbId" uuid NOT NULL,
        "ClientId" text NOT NULL,
        "TargetUri" character varying(2000) NOT NULL,
        "LogoutToken" character varying(8000) NOT NULL,
        "Sid" character varying(64),
        "Sub" character varying(200),
        "Status" character varying(20) NOT NULL,
        "AttemptCount" integer NOT NULL DEFAULT 0,
        "MaxAttempts" integer NOT NULL DEFAULT 5,
        "LastHttpStatus" integer,
        "LastError" character varying(1000),
        "CreatedAt" timestamp with time zone NOT NULL,
        "LastAttemptAt" timestamp with time zone,
        "NextAttemptAt" timestamp with time zone,
        CONSTRAINT "PK_BackchannelLogoutNotifications" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_BackchannelLogoutNotifications_Clients_ClientDbId" FOREIGN KEY ("ClientDbId") REFERENCES "Clients" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251002183251_Initial') THEN
    CREATE TABLE "ClientIdentityProviders" (
        "ClientId" uuid NOT NULL,
        "IdentityProviderId" uuid NOT NULL,
        "Enabled" boolean NOT NULL DEFAULT TRUE,
        "IsDefaultForClient" boolean NOT NULL DEFAULT FALSE,
        "AutoRedirectIfSingle" boolean NOT NULL DEFAULT FALSE,
        "RequiredAcr" character varying(100),
        "Order" integer NOT NULL DEFAULT 0,
        CONSTRAINT "PK_ClientIdentityProviders" PRIMARY KEY ("ClientId", "IdentityProviderId"),
        CONSTRAINT "FK_ClientIdentityProviders_Clients_ClientId" FOREIGN KEY ("ClientId") REFERENCES "Clients" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_ClientIdentityProviders_IdentityProviders_IdentityProviderId" FOREIGN KEY ("IdentityProviderId") REFERENCES "IdentityProviders" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251002183251_Initial') THEN
    CREATE TABLE "ClientJwksHistories" (
        "Id" uuid NOT NULL,
        "ClientId" uuid NOT NULL,
        "JwksJson" character varying(8000) NOT NULL,
        "Source" character varying(50),
        "Hash" character varying(64),
        "CreatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_ClientJwksHistories" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_ClientJwksHistories_Clients_ClientId" FOREIGN KEY ("ClientId") REFERENCES "Clients" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251002183251_Initial') THEN
    CREATE TABLE "ClientScopes" (
        "ClientId" uuid NOT NULL,
        "ScopeName" character varying(100) NOT NULL,
        CONSTRAINT "PK_ClientScopes" PRIMARY KEY ("ClientId", "ScopeName"),
        CONSTRAINT "FK_ClientScopes_Clients_ClientId" FOREIGN KEY ("ClientId") REFERENCES "Clients" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_ClientScopes_Scopes_ScopeName" FOREIGN KEY ("ScopeName") REFERENCES "Scopes" ("Name") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251002183251_Initial') THEN
    CREATE TABLE "Registrations" (
        "Id" uuid NOT NULL,
        "Email" character varying(256) NOT NULL,
        "NormalizedEmail" character varying(256) NOT NULL,
        "FirstName" character varying(100),
        "LastName" character varying(100),
        "ClientId" uuid,
        "PasswordHash" character varying(500),
        "State" character varying(20) NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "ApprovedAt" timestamp with time zone,
        "ApprovedByUserId" uuid,
        "RejectedAt" timestamp with time zone,
        "RejectedByUserId" uuid,
        CONSTRAINT "PK_Registrations" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Registrations_Clients_ClientId" FOREIGN KEY ("ClientId") REFERENCES "Clients" ("Id") ON DELETE SET NULL
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251002183251_Initial') THEN
    CREATE TABLE "UserClientAssignments" (
        "UserId" uuid NOT NULL,
        "ClientId" uuid NOT NULL,
        "RealmId" uuid NOT NULL,
        "IsActive" boolean NOT NULL,
        CONSTRAINT "PK_UserClientAssignments" PRIMARY KEY ("UserId", "ClientId", "RealmId"),
        CONSTRAINT "FK_UserClientAssignments_Clients_ClientId" FOREIGN KEY ("ClientId") REFERENCES "Clients" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_UserClientAssignments_Realms_RealmId" FOREIGN KEY ("RealmId") REFERENCES "Realms" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_UserClientAssignments_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251002183251_Initial') THEN
    CREATE TABLE "UserClientRoleAssignments" (
        "UserId" uuid NOT NULL,
        "RoleId" uuid NOT NULL,
        "ClientId" uuid NOT NULL,
        "IsActive" boolean NOT NULL,
        CONSTRAINT "PK_UserClientRoleAssignments" PRIMARY KEY ("UserId", "RoleId", "ClientId"),
        CONSTRAINT "FK_UserClientRoleAssignments_Clients_ClientId" FOREIGN KEY ("ClientId") REFERENCES "Clients" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_UserClientRoleAssignments_Roles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "Roles" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_UserClientRoleAssignments_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251002183251_Initial') THEN
    CREATE TABLE "UserRealmRoleAssignments" (
        "UserId" uuid NOT NULL,
        "RoleId" uuid NOT NULL,
        "RealmId" uuid NOT NULL,
        "IsActive" boolean NOT NULL,
        CONSTRAINT "PK_UserRealmRoleAssignments" PRIMARY KEY ("UserId", "RoleId", "RealmId"),
        CONSTRAINT "FK_UserRealmRoleAssignments_Realms_RealmId" FOREIGN KEY ("RealmId") REFERENCES "Realms" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_UserRealmRoleAssignments_Roles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "Roles" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_UserRealmRoleAssignments_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251002183251_Initial') THEN
    CREATE TABLE "UserRoleAssignments" (
        "UserId" uuid NOT NULL,
        "RoleId" uuid NOT NULL,
        "ClientId" uuid NOT NULL,
        "RealmId" uuid NOT NULL,
        "IsActive" boolean NOT NULL,
        CONSTRAINT "PK_UserRoleAssignments" PRIMARY KEY ("UserId", "RoleId", "ClientId", "RealmId"),
        CONSTRAINT "FK_UserRoleAssignments_Clients_ClientId" FOREIGN KEY ("ClientId") REFERENCES "Clients" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_UserRoleAssignments_Realms_RealmId" FOREIGN KEY ("RealmId") REFERENCES "Realms" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_UserRoleAssignments_Roles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "Roles" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_UserRoleAssignments_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251002183251_Initial') THEN
    CREATE UNIQUE INDEX "IX_AuthorizationCodes_Code" ON "AuthorizationCodes" ("Code");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251002183251_Initial') THEN
    CREATE INDEX "IX_BackchannelLogoutNotifications_ClientDbId" ON "BackchannelLogoutNotifications" ("ClientDbId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251002183251_Initial') THEN
    CREATE INDEX "IX_BackchannelLogoutNotifications_ClientId" ON "BackchannelLogoutNotifications" ("ClientId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251002183251_Initial') THEN
    CREATE INDEX "IX_BackchannelLogoutNotifications_Status_NextAttemptAt" ON "BackchannelLogoutNotifications" ("Status", "NextAttemptAt");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251002183251_Initial') THEN
    CREATE INDEX "IX_ClientIdentityProviders_IdentityProviderId" ON "ClientIdentityProviders" ("IdentityProviderId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251002183251_Initial') THEN
    CREATE INDEX "IX_ClientJwksHistories_ClientId_CreatedAt" ON "ClientJwksHistories" ("ClientId", "CreatedAt");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251002183251_Initial') THEN
    CREATE UNIQUE INDEX "IX_Clients_ClientId" ON "Clients" ("ClientId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251002183251_Initial') THEN
    CREATE INDEX "IX_Clients_RealmId" ON "Clients" ("RealmId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251002183251_Initial') THEN
    CREATE INDEX "IX_ClientScopes_ScopeName" ON "ClientScopes" ("ScopeName");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251002183251_Initial') THEN
    CREATE UNIQUE INDEX "IX_Consents_UserId_ClientId" ON "Consents" ("UserId", "ClientId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251002183251_Initial') THEN
    CREATE UNIQUE INDEX "IX_ExternalIdentities_Issuer_Subject" ON "ExternalIdentities" ("Issuer", "Subject");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251002183251_Initial') THEN
    CREATE INDEX "IX_ExternalIdentities_UserId" ON "ExternalIdentities" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251002183251_Initial') THEN
    CREATE INDEX "IX_IdentityProviderClaimMappings_IdentityProviderId" ON "IdentityProviderClaimMappings" ("IdentityProviderId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251002183251_Initial') THEN
    CREATE INDEX "IX_IdentityProviderKeys_Provider_Kid_CI" ON "IdentityProviderKeys" ("IdentityProviderId", "Kid");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251002183251_Initial') THEN
    CREATE UNIQUE INDEX "IX_IdentityProviders_Name" ON "IdentityProviders" ("Name");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251002183251_Initial') THEN
    CREATE INDEX "IX_LogoutRedirectReferences_ExpiresAt" ON "LogoutRedirectReferences" ("ExpiresAt");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251002183251_Initial') THEN
    CREATE INDEX "IX_PushedAuthorizationRequests_ExpiresAt" ON "PushedAuthorizationRequests" ("ExpiresAt");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251002183251_Initial') THEN
    CREATE UNIQUE INDEX "IX_QrLoginSessions_SessionToken" ON "QrLoginSessions" ("SessionToken");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251002183251_Initial') THEN
    CREATE INDEX "IX_QrLoginSessions_SessionTokenHash" ON "QrLoginSessions" ("SessionTokenHash");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251002183251_Initial') THEN
    CREATE INDEX "IX_QrLoginSessions_Status_ExpiresAt" ON "QrLoginSessions" ("Status", "ExpiresAt");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251002183251_Initial') THEN
    CREATE UNIQUE INDEX "IX_Realms_Name" ON "Realms" ("Name");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251002183251_Initial') THEN
    CREATE INDEX "IX_Registrations_ClientId" ON "Registrations" ("ClientId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251002183251_Initial') THEN
    CREATE INDEX "IX_Registrations_NormalizedEmail" ON "Registrations" ("NormalizedEmail");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251002183251_Initial') THEN
    CREATE INDEX "IX_RevocationAudits_TokenHash_ClientId" ON "RevocationAudits" ("TokenHash", "ClientId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251002183251_Initial') THEN
    CREATE UNIQUE INDEX "IX_Roles_RealmId_Name" ON "Roles" ("RealmId", "Name");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251002183251_Initial') THEN
    CREATE UNIQUE INDEX "IX_SigningKeys_Kid" ON "SigningKeys" ("Kid");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251002183251_Initial') THEN
    CREATE UNIQUE INDEX "IX_Tokens_TokenHash" ON "Tokens" ("TokenHash");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251002183251_Initial') THEN
    CREATE INDEX "IX_Tokens_UserId_ClientId_Type" ON "Tokens" ("UserId", "ClientId", "Type");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251002183251_Initial') THEN
    CREATE UNIQUE INDEX "IX_UserAlternativeEmails_NormalizedEmail" ON "UserAlternativeEmails" ("NormalizedEmail");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251002183251_Initial') THEN
    CREATE UNIQUE INDEX "IX_UserAlternativeEmails_UserId_NormalizedEmail" ON "UserAlternativeEmails" ("UserId", "NormalizedEmail");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251002183251_Initial') THEN
    CREATE INDEX "IX_UserClientAssignments_ClientId" ON "UserClientAssignments" ("ClientId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251002183251_Initial') THEN
    CREATE INDEX "IX_UserClientAssignments_RealmId" ON "UserClientAssignments" ("RealmId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251002183251_Initial') THEN
    CREATE INDEX "IX_UserClientRoleAssignments_ClientId" ON "UserClientRoleAssignments" ("ClientId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251002183251_Initial') THEN
    CREATE INDEX "IX_UserClientRoleAssignments_RoleId" ON "UserClientRoleAssignments" ("RoleId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251002183251_Initial') THEN
    CREATE INDEX "IX_UserRealmRoleAssignments_RealmId" ON "UserRealmRoleAssignments" ("RealmId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251002183251_Initial') THEN
    CREATE INDEX "IX_UserRealmRoleAssignments_RoleId" ON "UserRealmRoleAssignments" ("RoleId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251002183251_Initial') THEN
    CREATE INDEX "IX_UserRoleAssignments_ClientId" ON "UserRoleAssignments" ("ClientId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251002183251_Initial') THEN
    CREATE INDEX "IX_UserRoleAssignments_RealmId" ON "UserRoleAssignments" ("RealmId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251002183251_Initial') THEN
    CREATE INDEX "IX_UserRoleAssignments_RoleId" ON "UserRoleAssignments" ("RoleId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251002183251_Initial') THEN
    CREATE UNIQUE INDEX "IX_Users_NormalizedEmail" ON "Users" ("NormalizedEmail");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251002183251_Initial') THEN
    CREATE UNIQUE INDEX "IX_Users_Username" ON "Users" ("Username");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251002183251_Initial') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20251002183251_Initial', '9.0.9');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251002195948_QRLoginAndLatestChanges') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20251002195948_QRLoginAndLatestChanges', '9.0.9');
    END IF;
END $EF$;
COMMIT;

