// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MrWhoOidc.KeyGen.Persistence;

#nullable disable

namespace MrWhoOidc.KeyGen.Persistence.Migrations
{
    [DbContext(typeof(KeyGenDbContext))]
    partial class KeyGenDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("MrWhoOidc.KeyGen.Domain.Models.KeyDownloadRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("DownloadType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("DownloadedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DownloadedBy")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("KeyPairMetadataId")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DownloadedAt");

                    b.HasIndex("KeyPairMetadataId");

                    b.ToTable("KeyDownloadRecords");
                });

            modelBuilder.Entity("MrWhoOidc.KeyGen.Domain.Models.KeyPairMetadata", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Algorithm")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Curve")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("DownloadCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<int?>("KeySize")
                        .HasColumnType("INTEGER");

                    b.Property<string>("KeyType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("Kid")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("PublicKeyJwks")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("Active");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("Kid")
                        .IsUnique();

                    b.HasIndex("Status");

                    b.ToTable("KeyPairMetadata");
                });

            modelBuilder.Entity("MrWhoOidc.KeyGen.Domain.Models.LicenseTokenMetadata", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Features")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("GeneratedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("GeneratedBy")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Limits")
                        .HasColumnType("TEXT");

                    b.Property<string>("Organization")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Tier")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("TokenId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("ValidFrom")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("ValidUntil")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GeneratedAt");

                    b.HasIndex("Tier");

                    b.HasIndex("TokenId")
                        .IsUnique();

                    b.ToTable("LicenseTokenMetadata");
                });

            modelBuilder.Entity("MrWhoOidc.KeyGen.Domain.Models.KeyDownloadRecord", b =>
                {
                    b.HasOne("MrWhoOidc.KeyGen.Domain.Models.KeyPairMetadata", "KeyPairMetadata")
                        .WithMany("DownloadRecords")
                        .HasForeignKey("KeyPairMetadataId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KeyPairMetadata");
                });

            modelBuilder.Entity("MrWhoOidc.KeyGen.Domain.Models.KeyPairMetadata", b =>
                {
                    b.Navigation("DownloadRecords");
                });
#pragma warning restore 612, 618
        }
    }
}
