#!/usr/bin/env pwsh

[CmdletBinding()]
param(
    [string]$Alias = "mrwhooidc-local",
    [string]$SuiteHost = "www.certification.openid.net",
    [string]$BaseUrl = "https://localhost:8443",
    [string]$TenantSlug = "default",
    [string]$PublicServerBaseUrl,
    [string]$LocalServerBaseUrl,
    [string]$MtlsServerBaseUrl,
    [string]$OutputDir = ".\tools\certification\.generated"
)

$ErrorActionPreference = "Stop"

function Resolve-AbsolutePath {
    param(
        [Parameter(Mandatory = $true)]
        [string]$Path
    )

    if ([System.IO.Path]::IsPathRooted($Path)) {
        return [System.IO.Path]::GetFullPath($Path)
    }

    return [System.IO.Path]::GetFullPath((Join-Path (Get-Location) $Path))
}

function Normalize-BaseUrl {
    param(
        [Parameter(Mandatory = $true)]
        [string]$Url
    )

    return $Url.Trim().TrimEnd('/')
}

function Ensure-TrailingSlash {
    param(
        [Parameter(Mandatory = $true)]
        [string]$Url
    )

    return "$(Normalize-BaseUrl -Url $Url)/"
}

if ([string]::IsNullOrWhiteSpace($PublicServerBaseUrl)) {
    $PublicServerBaseUrl = $BaseUrl
}

if ([string]::IsNullOrWhiteSpace($LocalServerBaseUrl)) {
    $LocalServerBaseUrl = $PublicServerBaseUrl
}

if ([string]::IsNullOrWhiteSpace($MtlsServerBaseUrl)) {
    $MtlsServerBaseUrl = $PublicServerBaseUrl
}

$normalizedBaseUrl = Normalize-BaseUrl -Url $BaseUrl
$issuer = "$normalizedBaseUrl/t/$TenantSlug"
$discoveryUrl = "$issuer/.well-known/openid-configuration"
$jwksUrl = "$issuer/jwks"
$authorizeUrl = "$issuer/authorize"
$registrationUrl = "$issuer/register"
$endSessionUrl = "$issuer/connect/endsession"
$checkSessionUrl = "$issuer/connect/checksession"

$callbackUrl = "https://$SuiteHost/test/a/$Alias/callback"
$postLogoutRedirectUrl = "https://$SuiteHost/test/a/$Alias/post_logout_redirect"
$frontChannelLogoutUrl = "https://$SuiteHost/test/a/$Alias/frontchannel_logout"
$backChannelLogoutUrl = "https://$SuiteHost/test/a/$Alias/backchannel_logout"

$resolvedOutputDir = Resolve-AbsolutePath -Path $OutputDir
New-Item -ItemType Directory -Path $resolvedOutputDir -Force | Out-Null

$jsonPath = Join-Path $resolvedOutputDir "conformance-suite-inputs.json"
$notesPath = Join-Path $resolvedOutputDir "conformance-suite-notes.md"
$envPath = Join-Path $resolvedOutputDir "conformance-suite-env.ps1"
$expectedFailuresPath = Join-Path $resolvedOutputDir "expected-failures.json"
$expectedSkipsPath = Join-Path $resolvedOutputDir "expected-skips.json"

$runnerEnvironment = [ordered]@{
    CONFORMANCE_SERVER = Ensure-TrailingSlash -Url $PublicServerBaseUrl
    CONFORMANCE_SERVER_LOCAL = Ensure-TrailingSlash -Url $LocalServerBaseUrl
    CONFORMANCE_SERVER_MTLS = Ensure-TrailingSlash -Url $MtlsServerBaseUrl
}

$inputs = [ordered]@{
    generatedAtUtc = (Get-Date).ToUniversalTime().ToString("o")
    alias = $Alias
    suiteHost = $SuiteHost
    issuer = [ordered]@{
        baseUrl = $normalizedBaseUrl
        tenantSlug = $TenantSlug
        issuer = $issuer
        discovery = $discoveryUrl
        jwks = $jwksUrl
        authorize = $authorizeUrl
        registration = $registrationUrl
        endSession = $endSessionUrl
        checkSession = $checkSessionUrl
    }
    hostedSuite = [ordered]@{
        callback = $callbackUrl
        postLogoutRedirect = $postLogoutRedirectUrl
        frontChannelLogout = $frontChannelLogoutUrl
        backChannelLogout = $backChannelLogoutUrl
    }
    fallbackClients = @(
        [ordered]@{
            clientId = "oidf-basic-primary"
            clientSecret = "oidf-basic-primary-dev-secret"
            redirectUri = $callbackUrl
            postLogoutRedirectUri = $postLogoutRedirectUrl
            frontChannelLogoutUri = $frontChannelLogoutUrl
            backChannelLogoutUri = $backChannelLogoutUrl
        },
        [ordered]@{
            clientId = "oidf-basic-secondary"
            clientSecret = "oidf-basic-secondary-dev-secret"
            redirectUri = $callbackUrl
            postLogoutRedirectUri = $postLogoutRedirectUrl
            frontChannelLogoutUri = $frontChannelLogoutUrl
            backChannelLogoutUri = $backChannelLogoutUrl
        }
    )
    recommendedProfiles = @(
        "Config OP",
        "Basic OP",
        "Form Post OP"
    )
    runnerEnvironment = $runnerEnvironment
    runnerArtifacts = [ordered]@{
        expectedFailuresFile = $expectedFailuresPath
        expectedSkipsFile = $expectedSkipsPath
        notesFile = $notesPath
        envFile = $envPath
    }
}

$inputs | ConvertTo-Json -Depth 10 | Set-Content -Path $jsonPath

if (-not (Test-Path -Path $expectedFailuresPath)) {
    Set-Content -Path $expectedFailuresPath -Value "[]"
}

if (-not (Test-Path -Path $expectedSkipsPath)) {
    Set-Content -Path $expectedSkipsPath -Value "[]"
}

$envScript = @"
# Generated by prepare-conformance-suite.ps1

$env:CONFORMANCE_SERVER = '$($runnerEnvironment.CONFORMANCE_SERVER)'
$env:CONFORMANCE_SERVER_LOCAL = '$($runnerEnvironment.CONFORMANCE_SERVER_LOCAL)'
$env:CONFORMANCE_SERVER_MTLS = '$($runnerEnvironment.CONFORMANCE_SERVER_MTLS)'
"@
Set-Content -Path $envPath -Value $envScript

$notes = @"
# Conformance Suite Inputs

Generated: $($inputs.generatedAtUtc)

## Issuer

- Alias: $Alias
- Issuer: $issuer
- Discovery: $discoveryUrl
- JWKS: $jwksUrl
- Registration endpoint: $registrationUrl
- End-session endpoint: $endSessionUrl
- Check-session iframe: $checkSessionUrl

## Hosted Suite Values

- Callback URI: $callbackUrl
- Post-logout redirect URI: $postLogoutRedirectUrl
- Front-channel logout URI: $frontChannelLogoutUrl
- Back-channel logout URI: $backChannelLogoutUrl

## Fallback Clients

- oidf-basic-primary / oidf-basic-primary-dev-secret
- oidf-basic-secondary / oidf-basic-secondary-dev-secret

## Official Runner Environment

- CONFORMANCE_SERVER=$($runnerEnvironment.CONFORMANCE_SERVER)
- CONFORMANCE_SERVER_LOCAL=$($runnerEnvironment.CONFORMANCE_SERVER_LOCAL)
- CONFORMANCE_SERVER_MTLS=$($runnerEnvironment.CONFORMANCE_SERVER_MTLS)

## Generated Artifacts

- Inputs JSON: $jsonPath
- Environment script: $envPath
- Expected failures file: $expectedFailuresPath
- Expected skips file: $expectedSkipsPath

## Wrapper Usage

Example with the repo wrapper around the official run-test-plan.py script:

```powershell
pwsh ./tools/certification/invoke-official-run-test-plan.ps1 `
  -ConformanceSuitePath C:\src\conformance-suite `
  -Alias $Alias `
  -RunnerArguments @(
    '--list',
    '<test-plan expression as one string>',
    '<config-file path>'
  )
```

For actual execution, replace the placeholder plan expression and config-file path with the official conformance-suite values you are using.
"@
Set-Content -Path $notesPath -Value $notes

Write-Host "Rendered conformance suite inputs: $jsonPath" -ForegroundColor Green
Write-Host "Rendered runner environment script: $envPath" -ForegroundColor Green
Write-Host "Rendered hosted-suite notes: $notesPath" -ForegroundColor Green
Write-Host "Prepared expected-failures file: $expectedFailuresPath" -ForegroundColor Green
Write-Host "Prepared expected-skips file: $expectedSkipsPath" -ForegroundColor Green