#!/usr/bin/env bash
# =============================================================================
# setup-dev.sh — One-command local development setup for MrWhoOidc
# =============================================================================
# Generates a local HTTPS dev certificate, creates/updates the .env file with
# randomly generated dev secrets, and trusts the cert so browsers don't warn on
# https://localhost:8443.
#
# docker-compose.dev.yml has no literal secret defaults: it requires
#   DEV_CERT_PASSWORD, DEV_POSTGRES_PASSWORD, SEED_ADMIN_PASSWORD,
#   DEV_SEED_BLAZOR_WEB_CLIENT_SECRET, DEV_SEED_TEST_API_CLIENT_SECRET
# This script generates any of them that are missing from .env (existing values
# are kept, so re-running is safe and the certificate keeps its password).
#
# Usage:
#   bash scripts/setup-dev.sh
#
# Prerequisites: dotnet SDK 10.0+ (for dev-certs); openssl or /dev/urandom
# =============================================================================
set -euo pipefail

# --- Resolve repo root from script location ---
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

CERT_DIR="$REPO_ROOT/certs"
CERT_PATH="$CERT_DIR/aspnetapp.pfx"
ENV_FILE="$REPO_ROOT/.env"
ENV_EXAMPLE="$REPO_ROOT/.env.example"

# --- Colors ---
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

info()  { echo -e "${GREEN}[INFO]${NC} $1"; }
warn()  { echo -e "${YELLOW}[WARN]${NC} $1"; }
error() { echo -e "${RED}[ERROR]${NC} $1" >&2; }

# Random URL-safe string of length $1 (no characters Compose would interpolate or quote).
random_secret() {
    local len="$1" value=""
    while [[ ${#value} -lt $len ]]; do
        if command -v openssl >/dev/null 2>&1; then
            value+="$(openssl rand -base64 48 | tr -d '/+=\n')"
        else
            value+="$(head -c 48 /dev/urandom | base64 | tr -d '/+=\n')"
        fi
    done
    printf '%s' "${value:0:$len}"
}

# Value of KEY in .env (last assignment wins, like Compose), or empty.
env_get() {
    [[ -f "$ENV_FILE" ]] || return 0
    grep -E "^$1=" "$ENV_FILE" | tail -n 1 | cut -d= -f2- || true
}

# Set KEY=VALUE in .env, replacing an existing assignment or appending one.
env_set() {
    local key="$1" value="$2"
    if grep -qE "^$key=" "$ENV_FILE"; then
        sed -i.bak "s|^$key=.*|$key=$value|" "$ENV_FILE" && rm -f "$ENV_FILE.bak"
    else
        printf '%s=%s\n' "$key" "$value" >> "$ENV_FILE"
    fi
}

# Set KEY only when .env has no non-empty value for it. Prints whether it was generated.
env_ensure() {
    local key="$1" value="$2"
    if [[ -n "$(env_get "$key")" ]]; then
        info "  $key: kept existing value"
    else
        env_set "$key" "$value"
        info "  $key: generated"
        GENERATED_ANY=1
    fi
}

# --- Prerequisite checks ---
if ! command -v dotnet >/dev/null 2>&1; then
    error "dotnet SDK is not installed or not on PATH. Install .NET 10.0 SDK from https://dotnet.microsoft.com/download"
    exit 1
fi

info "dotnet found: $(dotnet --version)"

# --- Step 1: Create .env if missing ---
if [[ -f "$ENV_FILE" ]]; then
    info ".env already exists — keeping its values and adding any missing dev secrets."
else
    info "Creating .env from .env.example..."
    if [[ -f "$ENV_EXAMPLE" ]]; then
        cp "$ENV_EXAMPLE" "$ENV_FILE"
    else
        warn ".env.example not found — creating a minimal .env."
        echo "# Generated by scripts/setup-dev.sh — override values as needed." > "$ENV_FILE"
    fi
    chmod 600 "$ENV_FILE" 2>/dev/null || true

    env_set POSTGRES_PASSWORD "$(random_secret 32)"
    env_set OIDC_PUBLIC_BASE_URL "https://localhost:8443"
    # BOOTSTRAP_TOKEN — leave empty for dev (dev stack auto-seeds)
    if grep -qE "^BOOTSTRAP_TOKEN=" "$ENV_FILE"; then
        env_set BOOTSTRAP_TOKEN ""
    fi
fi

# --- Step 2: Dev secrets required by docker-compose.dev.yml ---
# The certificate password is reused when .env already has one, so an existing .env keeps matching.
CERT_PASSWORD="$(env_get DEV_CERT_PASSWORD)"
if [[ -z "$CERT_PASSWORD" ]]; then
    CERT_PASSWORD="$(env_get CERT_PASSWORD)"
fi
if [[ -z "$CERT_PASSWORD" ]]; then
    CERT_PASSWORD="$(random_secret 32)"
fi

GENERATED_ANY=0
info "Ensuring dev secrets in .env:"
env_ensure DEV_CERT_PASSWORD "$CERT_PASSWORD"
env_ensure CERT_PASSWORD "$CERT_PASSWORD"
env_ensure DEV_POSTGRES_PASSWORD "$(random_secret 32)"
# Admin password: random letters/digits plus fixed classes so any complexity policy is met.
env_ensure SEED_ADMIN_PASSWORD "Dev-$(random_secret 20)-9a"
env_ensure DEV_SEED_BLAZOR_WEB_CLIENT_SECRET "$(random_secret 64)"
env_ensure DEV_SEED_TEST_API_CLIENT_SECRET "$(random_secret 48)"

# --- Step 3: Generate dev HTTPS certificate (with the password stored in .env) ---
info "Generating local HTTPS dev certificate..."

mkdir -p "$CERT_DIR"

if [[ -f "$CERT_PATH" ]]; then
    warn "Certificate already exists at $CERT_PATH — regenerating."
    rm -f "$CERT_PATH"
fi

if ! dotnet dev-certs https -ep "$CERT_PATH" -p "$CERT_PASSWORD"; then
    error "Failed to generate dev certificate."
    exit 1
fi

# Make cert readable by the non-root container user (chmod 644 per certs/README.md)
chmod 644 "$CERT_PATH"
info "Dev certificate generated at: $CERT_PATH"

# --- Step 4: Trust the dev certificate ---
info "Trusting dev certificate..."

# On Linux, dotnet dev-certs https --trust may need SSL_CERT_DIR set (see certs/README.md).
# Export it for this session so trust works on Linux hosts.
if [[ "$(uname)" == "Linux" ]]; then
    export SSL_CERT_DIR="${SSL_CERT_DIR:-$HOME/.aspnet/dev-certs/trust:/usr/lib/ssl/certs}"
fi

dotnet dev-certs https --trust 2>/dev/null || warn "Could not auto-trust certificate. On Linux, run: dotnet dev-certs https --trust (after exporting SSL_CERT_DIR). On macOS, accept the Keychain prompt."

if [[ "$GENERATED_ANY" == "1" ]]; then
    echo ""
    warn "New dev secrets were generated. Existing dev volumes were initialized with the previous values"
    warn "(database password, seeded admin password and client secrets are only applied on first start)."
    warn "Reset the dev state once: docker compose -f docker-compose.dev.yml down -v"
fi

# --- Step 5: Print next steps ---
echo ""
info "=== Setup complete ==="
echo ""
echo "Dev admin login: admin@mrwho.local / value of SEED_ADMIN_PASSWORD in .env"
echo ""
echo "Next steps:"
echo "  1. Start the dev stack:"
echo "       docker compose -f docker-compose.dev.yml up -d --build"
echo ""
echo "  2. Verify the stack is running:"
echo "       curl -k https://localhost:8443/t/default/.well-known/openid-configuration"
echo "       bash scripts/verify-installation.sh"
echo ""
echo "  3. Stop the stack:"
echo "       docker compose -f docker-compose.dev.yml down"
echo ""
echo "To regenerate the cert, re-run this script. To rotate dev secrets, remove them from .env, re-run, and reset volumes (down -v)."
