#!/usr/bin/env pwsh
# =============================================================================
# setup-dev.ps1 — One-command local development setup for MrWhoOidc (Windows)
# =============================================================================
# Generates a local HTTPS dev certificate, creates a .env file with dev
# defaults, and trusts the cert so browsers don't warn on https://localhost:8443.
#
# Idempotent: safe to re-run; existing .env is not overwritten.
#
# Usage:
#   pwsh scripts/setup-dev.ps1
#   # or from PowerShell:
#   .\scripts\setup-dev.ps1
#
# Prerequisites: dotnet SDK 10.0+ (for dev-certs)
# =============================================================================
[CmdletBinding()]
param()
$ErrorActionPreference = "Stop"

# --- Resolve repo root from script location ---
$ScriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$RepoRoot = Resolve-Path "$ScriptDir\.."

$CertDir = Join-Path $RepoRoot "certs"
$CertPath = Join-Path $CertDir "aspnetapp.pfx"
$CertPassword = "changeit"
$EnvFile = Join-Path $RepoRoot ".env"
$EnvExample = Join-Path $RepoRoot ".env.example"

function Write-Info([string]$msg) { Write-Host "[INFO] $msg" -ForegroundColor Green }
function Write-Warn([string]$msg) { Write-Host "[WARN] $msg" -ForegroundColor Yellow }
function Write-Err([string]$msg)  { Write-Host "[ERROR] $msg" -ForegroundColor Red }

# --- Prerequisite checks ---
if (-not (Get-Command dotnet -ErrorAction SilentlyContinue)) {
    Write-Err "dotnet SDK is not installed or not on PATH. Install .NET 10.0 SDK from https://dotnet.microsoft.com/download"
    exit 1
}

Write-Info "dotnet found: $(& dotnet --version)"

# --- Step 1: Generate dev HTTPS certificate ---
Write-Info "Generating local HTTPS dev certificate..."

if (-not (Test-Path $CertDir)) {
    New-Item -ItemType Directory -Path $CertDir -Force | Out-Null
}

if (Test-Path $CertPath) {
    Write-Warn "Certificate already exists at $CertPath — regenerating."
    Remove-Item $CertPath -Force
}

& dotnet dev-certs https -ep $CertPath -p $CertPassword
if ($LASTEXITCODE -ne 0) {
    Write-Err "Failed to generate dev certificate."
    exit 1
}

Write-Info "Dev certificate generated at: $CertPath"

# --- Step 2: Trust the dev certificate ---
Write-Info "Trusting dev certificate..."

& dotnet dev-certs https --trust
if ($LASTEXITCODE -ne 0) {
    Write-Warn "Could not auto-trust certificate. On Windows, accept the certificate prompt. On WSL/Linux, run: dotnet dev-certs https --trust (after exporting SSL_CERT_DIR)."
}

# --- Step 3: Create .env file with dev defaults ---
if (Test-Path $EnvFile) {
    Write-Info ".env already exists — leaving it untouched. To regenerate, delete it and re-run."
} else {
    Write-Info "Creating .env with dev defaults from .env.example..."

    if (Test-Path $EnvExample) {
        Copy-Item $EnvExample $EnvFile
    } else {
        Write-Warn ".env.example not found — creating a minimal .env."
        "# Generated by scripts/setup-dev.ps1" | Out-File -FilePath $EnvFile -Encoding utf8
    }

    # Generate a strong random POSTGRES_PASSWORD
    $pgPassBytes = New-Object byte[] 24
    [System.Security.Cryptography.RandomNumberGenerator]::Create().GetBytes($pgPassBytes)
    $PgPass = [Convert]::ToBase64String($pgPassBytes) -replace '[/+=]', ''

    $envContent = Get-Content $EnvFile

    # POSTGRES_PASSWORD — replace placeholder with a strong random value
    $envContent = $envContent -replace '^POSTGRES_PASSWORD=.*', "POSTGRES_PASSWORD=$PgPass"
    # CERT_PASSWORD — set to match the generated cert
    $envContent = $envContent -replace '^CERT_PASSWORD=.*', "CERT_PASSWORD=$CertPassword"
    # OIDC_PUBLIC_BASE_URL — dev default
    $envContent = $envContent -replace '^OIDC_PUBLIC_BASE_URL=.*', "OIDC_PUBLIC_BASE_URL=https://localhost:8443"
    # BOOTSTRAP_TOKEN — leave empty for dev (dev stack auto-seeds)
    $envContent = $envContent -replace '^BOOTSTRAP_TOKEN=.*', "BOOTSTRAP_TOKEN="

    # Ensure required keys exist if .env.example was missing lines
    if ($envContent -notmatch '^POSTGRES_PASSWORD=') { $envContent += "POSTGRES_PASSWORD=$PgPass" }
    if ($envContent -notmatch '^CERT_PASSWORD=')     { $envContent += "CERT_PASSWORD=$CertPassword" }
    if ($envContent -notmatch '^OIDC_PUBLIC_BASE_URL=') { $envContent += "OIDC_PUBLIC_BASE_URL=https://localhost:8443" }

    $envContent | Out-File -FilePath $EnvFile -Encoding utf8

    Write-Info ".env created at: $EnvFile"
    Write-Info "  POSTGRES_PASSWORD: (randomly generated — see .env)"
    Write-Info "  CERT_PASSWORD: $CertPassword"
    Write-Info "  OIDC_PUBLIC_BASE_URL: https://localhost:8443"
}

# --- Step 4: Print next steps ---
Write-Host ""
Write-Info "=== Setup complete ==="
Write-Host ""
Write-Host "Next steps:"
Write-Host "  1. Start the dev stack:"
Write-Host "       docker compose -f docker-compose.dev.yml up -d --build"
Write-Host ""
Write-Host "  2. Verify the stack is running:"
Write-Host "       curl -k https://localhost:8443/t/default/.well-known/openid-configuration"
Write-Host "       bash scripts/verify-installation.sh"
Write-Host ""
Write-Host "  3. Stop the stack:"
Write-Host "       docker compose -f docker-compose.dev.yml down"
Write-Host ""
Write-Host "To regenerate the cert or .env, delete certs/aspnetapp.pfx or .env and re-run this script."