#!/usr/bin/env bash
# =============================================================================
# setup-dev.sh — One-command local development setup for MrWhoOidc
# =============================================================================
# Generates a local HTTPS dev certificate, creates a .env file with dev
# defaults, and trusts the cert so browsers don't warn on https://localhost:8443.
#
# Idempotent: safe to re-run; existing .env is not overwritten.
#
# Usage:
#   bash scripts/setup-dev.sh
#
# Prerequisites: dotnet SDK 10.0+ (for dev-certs), openssl (for random passwords)
# =============================================================================
set -euo pipefail

# --- Resolve repo root from script location ---
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

CERT_DIR="$REPO_ROOT/certs"
CERT_PATH="$CERT_DIR/aspnetapp.pfx"
CERT_PASSWORD="changeit"
ENV_FILE="$REPO_ROOT/.env"
ENV_EXAMPLE="$REPO_ROOT/.env.example"

# --- Colors ---
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

info()  { echo -e "${GREEN}[INFO]${NC} $1"; }
warn()  { echo -e "${YELLOW}[WARN]${NC} $1"; }
error() { echo -e "${RED}[ERROR]${NC} $1" >&2; }

# --- Prerequisite checks ---
if ! command -v dotnet >/dev/null 2>&1; then
    error "dotnet SDK is not installed or not on PATH. Install .NET 10.0 SDK from https://dotnet.microsoft.com/download"
    exit 1
fi

info "dotnet found: $(dotnet --version)"

# --- Step 1: Generate dev HTTPS certificate ---
info "Generating local HTTPS dev certificate..."

mkdir -p "$CERT_DIR"

if [[ -f "$CERT_PATH" ]]; then
    warn "Certificate already exists at $CERT_PATH — regenerating."
    rm -f "$CERT_PATH"
fi

dotnet dev-certs https -ep "$CERT_PATH" -p "$CERT_PASSWORD"
if [[ $? -ne 0 ]]; then
    error "Failed to generate dev certificate."
    exit 1
fi

# Make cert readable by the non-root container user (chmod 644 per certs/README.md)
chmod 644 "$CERT_PATH"
info "Dev certificate generated at: $CERT_PATH"

# --- Step 2: Trust the dev certificate ---
info "Trusting dev certificate..."

# On Linux, dotnet dev-certs https --trust may need SSL_CERT_DIR set (see certs/README.md).
# Export it for this session so trust works on Linux hosts.
if [[ "$(uname)" == "Linux" ]]; then
    export SSL_CERT_DIR="${SSL_CERT_DIR:-$HOME/.aspnet/dev-certs/trust:/usr/lib/ssl/certs}"
fi

dotnet dev-certs https --trust 2>/dev/null || warn "Could not auto-trust certificate. On Linux, run: dotnet dev-certs https --trust (after exporting SSL_CERT_DIR). On macOS, accept the Keychain prompt."

# --- Step 3: Create .env file with dev defaults ---
if [[ -f "$ENV_FILE" ]]; then
    info ".env already exists — leaving it untouched. To regenerate, delete it and re-run."
else
    info "Creating .env with dev defaults from .env.example..."

    if [[ ! -f "$ENV_EXAMPLE" ]]; then
        warn ".env.example not found — creating a minimal .env."
        cat > "$ENV_FILE" << 'EOF'
# Generated by scripts/setup-dev.sh — override values as needed.
EOF
    else
        cp "$ENV_EXAMPLE" "$ENV_FILE"
    fi

    # Generate a strong random POSTGRES_PASSWORD if openssl is available
    if command -v openssl >/dev/null 2>&1; then
        PG_PASS="$(openssl rand -base64 32 | tr -d '/+=' | head -c 32)"
    else
        PG_PASS="DevPass_$(date +%s)"
    fi

    # Set/replace dev values in .env
    # POSTGRES_PASSWORD — replace placeholder with a strong random value
    if grep -q "^POSTGRES_PASSWORD=" "$ENV_FILE"; then
        sed -i.bak "s|^POSTGRES_PASSWORD=.*|POSTGRES_PASSWORD=${PG_PASS}|" "$ENV_FILE" && rm -f "$ENV_FILE.bak"
    else
        echo "POSTGRES_PASSWORD=${PG_PASS}" >> "$ENV_FILE"
    fi

    # CERT_PASSWORD — set to match the generated cert
    if grep -q "^CERT_PASSWORD=" "$ENV_FILE"; then
        sed -i.bak "s|^CERT_PASSWORD=.*|CERT_PASSWORD=${CERT_PASSWORD}|" "$ENV_FILE" && rm -f "$ENV_FILE.bak"
    else
        echo "CERT_PASSWORD=${CERT_PASSWORD}" >> "$ENV_FILE"
    fi

    # OIDC_PUBLIC_BASE_URL — dev default
    if grep -q "^OIDC_PUBLIC_BASE_URL=" "$ENV_FILE"; then
        sed -i.bak "s|^OIDC_PUBLIC_BASE_URL=.*|OIDC_PUBLIC_BASE_URL=https://localhost:8443|" "$ENV_FILE" && rm -f "$ENV_FILE.bak"
    else
        echo "OIDC_PUBLIC_BASE_URL=https://localhost:8443" >> "$ENV_FILE"
    fi

    # BOOTSTRAP_TOKEN — leave empty for dev (dev stack auto-seeds)
    if grep -q "^BOOTSTRAP_TOKEN=" "$ENV_FILE"; then
        sed -i.bak "s|^BOOTSTRAP_TOKEN=.*|BOOTSTRAP_TOKEN=|" "$ENV_FILE" && rm -f "$ENV_FILE.bak"
    fi

    info ".env created at: $ENV_FILE"
    info "  POSTGRES_PASSWORD: (randomly generated — see .env)"
    info "  CERT_PASSWORD: $CERT_PASSWORD"
    info "  OIDC_PUBLIC_BASE_URL: https://localhost:8443"
fi

# --- Step 4: Print next steps ---
echo ""
info "=== Setup complete ==="
echo ""
echo "Next steps:"
echo "  1. Start the dev stack:"
echo "       docker compose -f docker-compose.dev.yml up -d --build"
echo ""
echo "  2. Verify the stack is running:"
echo "       curl -k https://localhost:8443/t/default/.well-known/openid-configuration"
echo "       bash scripts/verify-installation.sh"
echo ""
echo "  3. Stop the stack:"
echo "       docker compose -f docker-compose.dev.yml down"
echo ""
echo "To regenerate the cert or .env, delete certs/aspnetapp.pfx or .env and re-run this script."