#!/usr/bin/env pwsh
# =============================================================================
# setup-dev.ps1 — One-command local development setup for MrWhoOidc (Windows)
# =============================================================================
# Generates a local HTTPS dev certificate, creates/updates the .env file with
# randomly generated dev secrets, and trusts the cert so browsers don't warn on
# https://localhost:8443.
#
# docker-compose.dev.yml has no literal secret defaults: it requires
#   DEV_CERT_PASSWORD, DEV_POSTGRES_PASSWORD, SEED_ADMIN_PASSWORD,
#   DEV_SEED_BLAZOR_WEB_CLIENT_SECRET, DEV_SEED_TEST_API_CLIENT_SECRET
# This script generates any of them that are missing from .env (existing values
# are kept, so re-running is safe and the certificate keeps its password).
#
# Usage:
#   pwsh scripts/setup-dev.ps1
#   # or from PowerShell:
#   .\scripts\setup-dev.ps1
#
# Prerequisites: dotnet SDK 10.0+ (for dev-certs)
# =============================================================================
[CmdletBinding()]
param()
$ErrorActionPreference = "Stop"

# --- Resolve repo root from script location ---
$ScriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$RepoRoot = Resolve-Path "$ScriptDir\.."

$CertDir = Join-Path $RepoRoot "certs"
$CertPath = Join-Path $CertDir "aspnetapp.pfx"
$EnvFile = Join-Path $RepoRoot ".env"
$EnvExample = Join-Path $RepoRoot ".env.example"

function Write-Info([string]$msg) { Write-Host "[INFO] $msg" -ForegroundColor Green }
function Write-Warn([string]$msg) { Write-Host "[WARN] $msg" -ForegroundColor Yellow }
function Write-Err([string]$msg)  { Write-Host "[ERROR] $msg" -ForegroundColor Red }

# Random URL-safe string (no characters Compose would interpolate or quote).
function New-RandomSecret([int]$Length) {
    $value = ""
    while ($value.Length -lt $Length) {
        $bytes = New-Object byte[] 48
        [System.Security.Cryptography.RandomNumberGenerator]::Create().GetBytes($bytes)
        $value += ([Convert]::ToBase64String($bytes) -replace '[/+=]', '')
    }
    return $value.Substring(0, $Length)
}

# .env helpers (last assignment wins, like Compose). Written as UTF-8 without BOM.
function Get-EnvLines { if (Test-Path $EnvFile) { return @(Get-Content $EnvFile) } else { return @() } }
function Save-EnvLines([string[]]$Lines) { [System.IO.File]::WriteAllLines($EnvFile, $Lines, (New-Object System.Text.UTF8Encoding($false))) }

function Get-EnvValue([string]$Key) {
    $match = Get-EnvLines | Where-Object { $_ -match "^$([regex]::Escape($Key))=" } | Select-Object -Last 1
    if ($null -eq $match) { return "" }
    return $match.Substring($Key.Length + 1)
}

function Set-EnvValue([string]$Key, [string]$Value) {
    $lines = @(Get-EnvLines)
    $pattern = "^$([regex]::Escape($Key))="
    if ($lines | Where-Object { $_ -match $pattern }) {
        $lines = @($lines | ForEach-Object { if ($_ -match $pattern) { "$Key=$Value" } else { $_ } })
    } else {
        $lines += "$Key=$Value"
    }
    Save-EnvLines $lines
}

$script:GeneratedAny = $false
function Confirm-EnvValue([string]$Key, [string]$Value) {
    if ([string]::IsNullOrEmpty((Get-EnvValue $Key))) {
        Set-EnvValue $Key $Value
        Write-Info "  ${Key}: generated"
        $script:GeneratedAny = $true
    } else {
        Write-Info "  ${Key}: kept existing value"
    }
}

# --- Prerequisite checks ---
if (-not (Get-Command dotnet -ErrorAction SilentlyContinue)) {
    Write-Err "dotnet SDK is not installed or not on PATH. Install .NET 10.0 SDK from https://dotnet.microsoft.com/download"
    exit 1
}

Write-Info "dotnet found: $(& dotnet --version)"

# --- Step 1: Create .env if missing ---
if (Test-Path $EnvFile) {
    Write-Info ".env already exists — keeping its values and adding any missing dev secrets."
} else {
    Write-Info "Creating .env from .env.example..."
    if (Test-Path $EnvExample) {
        Save-EnvLines @(Get-Content $EnvExample)
    } else {
        Write-Warn ".env.example not found — creating a minimal .env."
        Save-EnvLines @("# Generated by scripts/setup-dev.ps1 — override values as needed.")
    }

    Set-EnvValue "POSTGRES_PASSWORD" (New-RandomSecret 32)
    Set-EnvValue "OIDC_PUBLIC_BASE_URL" "https://localhost:8443"
    # BOOTSTRAP_TOKEN — leave empty for dev (dev stack auto-seeds)
    if (Get-EnvLines | Where-Object { $_ -match '^BOOTSTRAP_TOKEN=' }) { Set-EnvValue "BOOTSTRAP_TOKEN" "" }
}

# --- Step 2: Dev secrets required by docker-compose.dev.yml ---
# The certificate password is reused when .env already has one, so an existing .env keeps matching.
$CertPassword = Get-EnvValue "DEV_CERT_PASSWORD"
if ([string]::IsNullOrEmpty($CertPassword)) { $CertPassword = Get-EnvValue "CERT_PASSWORD" }
if ([string]::IsNullOrEmpty($CertPassword)) { $CertPassword = New-RandomSecret 32 }

Write-Info "Ensuring dev secrets in .env:"
Confirm-EnvValue "DEV_CERT_PASSWORD" $CertPassword
Confirm-EnvValue "CERT_PASSWORD" $CertPassword
Confirm-EnvValue "DEV_POSTGRES_PASSWORD" (New-RandomSecret 32)
# Admin password: random letters/digits plus fixed classes so any complexity policy is met.
Confirm-EnvValue "SEED_ADMIN_PASSWORD" ("Dev-" + (New-RandomSecret 20) + "-9a")
Confirm-EnvValue "DEV_SEED_BLAZOR_WEB_CLIENT_SECRET" (New-RandomSecret 64)
Confirm-EnvValue "DEV_SEED_TEST_API_CLIENT_SECRET" (New-RandomSecret 48)

# --- Step 3: Generate dev HTTPS certificate (with the password stored in .env) ---
Write-Info "Generating local HTTPS dev certificate..."

if (-not (Test-Path $CertDir)) {
    New-Item -ItemType Directory -Path $CertDir -Force | Out-Null
}

if (Test-Path $CertPath) {
    Write-Warn "Certificate already exists at $CertPath — regenerating."
    Remove-Item $CertPath -Force
}

& dotnet dev-certs https -ep $CertPath -p $CertPassword
if ($LASTEXITCODE -ne 0) {
    Write-Err "Failed to generate dev certificate."
    exit 1
}

Write-Info "Dev certificate generated at: $CertPath"

# --- Step 4: Trust the dev certificate ---
Write-Info "Trusting dev certificate..."

& dotnet dev-certs https --trust
if ($LASTEXITCODE -ne 0) {
    Write-Warn "Could not auto-trust certificate. On Windows, accept the certificate prompt. On WSL/Linux, run: dotnet dev-certs https --trust (after exporting SSL_CERT_DIR)."
}

if ($script:GeneratedAny) {
    Write-Host ""
    Write-Warn "New dev secrets were generated. Existing dev volumes were initialized with the previous values"
    Write-Warn "(database password, seeded admin password and client secrets are only applied on first start)."
    Write-Warn "Reset the dev state once: docker compose -f docker-compose.dev.yml down -v"
}

# --- Step 5: Print next steps ---
Write-Host ""
Write-Info "=== Setup complete ==="
Write-Host ""
Write-Host "Dev admin login: admin@mrwho.local / value of SEED_ADMIN_PASSWORD in .env"
Write-Host ""
Write-Host "Next steps:"
Write-Host "  1. Start the dev stack:"
Write-Host "       docker compose -f docker-compose.dev.yml up -d --build"
Write-Host ""
Write-Host "  2. Verify the stack is running:"
Write-Host "       curl -k https://localhost:8443/t/default/.well-known/openid-configuration"
Write-Host "       bash scripts/verify-installation.sh"
Write-Host ""
Write-Host "  3. Stop the stack:"
Write-Host "       docker compose -f docker-compose.dev.yml down"
Write-Host ""
Write-Host "To regenerate the cert, re-run this script. To rotate dev secrets, remove them from .env, re-run, and reset volumes (down -v)."
